export const pl: Record<string, string> = {
  "Home": "Główna",
  "Dashboard": "Pulpit",
  "Train": "Trenuj",
  "Analyse": "Analizuj",
  "Resume": "Wznów",
  "Chest": "Klatka piersiowa",
  "Lats": "Mięśnie najszersze grzbietu",
  "Upper back": "Górna część pleców",
  "Lower back": "Dolna część pleców",
  "Traps": "Mięśnie czworoboczne",
  "Shoulders": "Barki",
  "Biceps": "Biceps",
  "Triceps": "Triceps",
  "Forearms": "Przedramiona",
  "Abs": "Brzuch",
  "Quads": "Mięśnie czworogłowe uda",
  "Hamstrings": "Mięśnie dwugłowe uda",
  "Glutes": "Pośladki",
  "Calves": "Łydki",
  "Full body": "Całe ciało",
  "Cardio": "Kardio",
  "Bodyweight": "Masa ciała",
  "Barbell": "Sztanga",
  "Dumbbell": "Hantel",
  "Kettlebell": "Odważnik kettlebell",
  "Machine": "Maszyna",
  "Cable": "Wyciąg",
  "Band": "Guma oporowa",
  "Plate": "Talerz",
  "Other": "Inne",
  "EZ bar": "Gryf łamany",
  "Dumbbells": "Hantle",
  "Kettlebells": "Odważniki kettlebell",
  "Flat bench": "Ławka płaska",
  "Adjustable bench": "Ławka regulowana",
  "Squat rack": "Stojak do przysiadów",
  "Pull-up bar": "Drążek do podciągania",
  "Dip station": "Poręcze do dipów",
  "Leg press": "Suwnica",
  "Leg extension": "Maszyna do prostowania nóg",
  "Leg curl": "Maszyna do uginania nóg",
  "Calf raise machine": "Maszyna do wspięć na palce",
  "Smith machine": "Suwnica Smitha",
  "Chest press machine": "Maszyna do wyciskania na klatkę",
  "Pec deck": "Maszyna do rozpiętek",
  "Shoulder press machine": "Maszyna do wyciskania na barki",
  "Assisted pull-up machine": "Maszyna do podciągania z asystą",
  "Cable station": "Brama z wyciągami",
  "Lat pulldown": "Wyciąg górny",
  "Seated row": "Wyciąg dolny",
  "Treadmill": "Bieżnia",
  "Rowing machine": "Ergometr wioślarski",
  "Stationary bike": "Rower stacjonarny",
  "Resistance band": "Guma oporowa",
  "Ab wheel": "Kółko do ćwiczeń brzucha",
  "Jump rope": "Skakanka",
  "Free weights": "Wolne ciężary",
  "Benches and racks": "Ławki i stojaki",
  "Machines": "Maszyny",
  "Accessories": "Akcesoria",
  "Beginner": "Początkujący",
  "Intermediate": "Średniozaawansowany",
  "Advanced": "Zaawansowany",
  "Weight & reps": "Ciężar i powtórzenia",
  "Reps only": "Tylko powtórzenia",
  "Distance & time": "Dystans i czas",
  "Warm-up": "Rozgrzewka",
  "Working set": "Seria robocza",
  "Drop set": "Seria ze zmniejszanym ciężarem",
  "To failure": "Do upadku mięśniowego",
  "Run": "Bieg",
  "Ride": "Jazda na rowerze",
  "Walk": "Spacer",
  "Hike": "Wędrówka",
  "Swim": "Pływanie",
  "Row": "Wiosłowanie",
  "Gym enthusiast": "Miłośnik siłowni",
  "Professional trainer": "Trener personalny",
  "Nutritionist": "Dietetyk",
  "Psychologist": "Psycholog",
  "Physical therapist": "Fizjoterapeuta",
  "4 weeks": "4 tygodnie",
  "12 weeks": "12 tygodni",
  "6 months": "6 miesięcy",
  "1 year": "1 rok",
  "A new version of FitTune is ready": "Nowa wersja FitTune jest gotowa",
  "Change password": "Zmień hasło",
  "Changing…": "Zmienianie…",
  "Choose a place to match exercises to the equipment available.": "Wybierz miejsce, aby dopasować ćwiczenia do dostępnego sprzętu.",
  "Clear": "Wyczyść",
  "Confirm new password": "Potwierdź nowe hasło",
  "Couldn't archive the exercise.": "Nie udało się zarchiwizować ćwiczenia.",
  "Couldn't archive this place. Try again.": "Nie udało się zarchiwizować tego miejsca. Spróbuj ponownie.",
  "Couldn't delete the routine.": "Nie udało się usunąć planu.",
  "Couldn't delete the workout.": "Nie udało się usunąć treningu.",
  "Couldn't discard the saved workout. Try again when you're online.": "Nie udało się odrzucić zapisanego treningu. Spróbuj ponownie po połączeniu z internetem.",
  "Couldn't load that workout. Check your connection.": "Nie udało się wczytać treningu. Sprawdź połączenie.",
  "Couldn't save the routine.": "Nie udało się zapisać planu.",
  "Create account": "Utwórz konto",
  "Create exercise": "Utwórz ćwiczenie",
  "Creating account…": "Tworzenie konta…",
  "Current password": "Obecne hasło",
  "Delete forever": "Usuń na zawsze",
  "Deleting…": "Usuwanie…",
  "Edit activity": "Edytuj aktywność",
  "Edit place": "Edytuj miejsce",
  "Estimated 1RM": "Szacowane 1RM",
  "Exercise archived. Past workouts keep it.": "Ćwiczenie zarchiwizowane. Pozostanie w poprzednich treningach.",
  "Exercise created": "Utworzono ćwiczenie",
  "Exercise updated": "Zaktualizowano ćwiczenie",
  "Farthest set": "Najdalsza seria",
  "Finish or discard your current workout first.": "Najpierw zakończ lub odrzuć bieżący trening.",
  "In progress": "W trakcie",
  "It": "To",
  "Load more": "Wczytaj więcej",
  "Loading places…": "Wczytywanie miejsc…",
  "Loading…": "Wczytywanie…",
  "Longest set": "Najdłuższa seria",
  "Month": "Miesiąc",
  "Muscles & demo": "Mięśnie i pokaz",
  "New password": "Nowe hasło",
  "No cached places yet. Connect to load them.": "Brak zapisanych miejsc. Połącz się z internetem, aby je wczytać.",
  "No exercises": "Brak ćwiczeń",
  "No previous set": "Brak poprzedniej serii",
  "Not synced on this device yet. Sync before you train somewhere without signal.": "Dane nie zostały jeszcze zsynchronizowane na tym urządzeniu. Zrób to przed treningiem bez zasięgu.",
  "Off": "Wyłączony",
  "Password changed. Other devices were signed out.": "Hasło zmienione. Inne urządzenia zostały wylogowane.",
  "Place added": "Dodano miejsce",
  "Place archived. Workouts keep their saved setup.": "Miejsce zarchiwizowane. Treningi zachowają zapisany zestaw sprzętu.",
  "Place updated. Existing workouts keep their setup.": "Miejsce zaktualizowane. Istniejące treningi zachowają swój zestaw sprzętu.",
  "Profile saved": "Zapisano profil",
  "Rest over - next set!": "Przerwa minęła - czas na kolejną serię!",
  "Routine": "Plan",
  "Routine created": "Utworzono plan",
  "Routine deleted": "Usunięto plan",
  "Routine saved": "Zapisano plan",
  "Save changes": "Zapisz zmiany",
  "Save place": "Zapisz miejsce",
  "Save profile": "Zapisz profil",
  "Save routine": "Zapisz plan",
  "Saved as routine": "Zapisano jako plan",
  "Saved on this device and waiting to sync.": "Zapisano na tym urządzeniu. Oczekuje na synchronizację.",
  "Saving…": "Zapisywanie…",
  "Seconds": "Sekundy",
  "Select all": "Zaznacz wszystkie",
  "Select exercises": "Wybierz ćwiczenia",
  "Session": "Sesja",
  "Session summary": "Podsumowanie sesji",
  "Signing in…": "Logowanie…",
  "Something went wrong.": "Coś poszło nie tak.",
  "Sync now": "Synchronizuj teraz",
  "Syncing…": "Synchronizowanie…",
  "Today": "Dzisiaj",
  "Total reps": "Łączna liczba powtórzeń",
  "Training volume": "Objętość treningowa",
  "Update": "Aktualizuj",
  "Week of": "Tydzień od",
  "Workout deleted": "Usunięto trening",
  "Workout places": "Miejsca treningu",
  "Workout so far": "Dotychczasowy trening",
  "Your account and all its data were deleted.": "Twoje konto i wszystkie jego dane zostały usunięte.",
  "Your session is saved.": "Trening został zapisany.",
  " +{count} more": " +{count} więcej",
  "No equipment": "Bez sprzętu",
  "Gym": "Siłownia",
  "Morning": "rano",
  "Afternoon": "po południu",
  "Evening": "wieczorem",
  "{part} {activity}": "Aktywność: {activity} ({part})",
  "Saved": "Zapisano",
  "Waiting to save": "Oczekiwanie na zapis",
  "Offline - saved on this device": "Offline - zapisano na tym urządzeniu",
  "Not saved": "Nie zapisano",
  "Yesterday": "Wczoraj",
  "just now": "przed chwilą",
  "{count} min ago": "{count} min temu",
  "{count} h ago": "{count} godz. temu",
  "Late session": "Późny trening",
  "Good morning": "Dzień dobry",
  "Good afternoon": "Dzień dobry",
  "Good evening": "Dobry wieczór",
  "Last synced {when}.": "Ostatnia synchronizacja: {when}.",
  "This is not saved on this device yet. {status} It will be available offline after the next sync.": "Tych danych nie zapisano jeszcze na tym urządzeniu. {status} Będą dostępne offline po następnej synchronizacji.",
  "FitTune's servers cannot be reached.": "Nie można połączyć się z serwerami FitTune.",
  "You are offline.": "Brak połączenia z internetem.",
  "Items not downloaded: {count}. Try again later.": "Nie pobrano elementów: {count}. Spróbuj ponownie później.",
  "Can't reach FitTune right now.": "Nie można teraz połączyć się z FitTune.",
  "Sync failed. Try again later.": "Synchronizacja nie powiodła się. Spróbuj ponownie później.",
  "Something went wrong. Please try again.": "Coś poszło nie tak. Spróbuj ponownie.",
  "Show {title} as a table": "Pokaż {title} jako tabelę",
  "Show {title} as a chart": "Pokaż {title} jako wykres",
  "Couldn't save the activity.": "Nie udało się zapisać aktywności.",
  "Couldn't delete the activity.": "Nie udało się usunąć aktywności.",
  "Unsynced workouts: {count}. Signing out will delete them from this device.": "Niezsynchronizowane treningi: {count}. Wylogowanie usunie je z tego urządzenia.",
  "FitTune keeps your exercises, routines, places and last {count} workouts on this device. They sync automatically when you open the app online.": "FitTune przechowuje ćwiczenia, plany, miejsca i ostatnie treningi ({count}) na tym urządzeniu. Synchronizują się automatycznie po otwarciu aplikacji online.",
  "Maximum places: {count}. Archive one to add another.": "Maksymalna liczba miejsc: {count}. Zarchiwizuj jedno, aby dodać kolejne.",
  "Exercises to delete: {count}. Their sets will also be deleted. This can't be undone.": "Ćwiczenia do usunięcia: {count}. Ich serie również zostaną usunięte. Tej czynności nie można cofnąć.",
  "Sets: {done}/{total}": "Serie: {done}/{total}",
  "Sets: {count}": "Serie: {count}",
  "Unfinished sets: {count}. They won't count towards your stats.": "Niedokończone serie: {count}. Nie zostaną uwzględnione w statystykach.",
  "Workouts: {count}": "Treningi: {count}",
  "Exercises: {count}": "Ćwiczenia: {count}",
  "Add exercises: {count}": "Dodaj ćwiczenia: {count}",
  "Completed sets: {sets}. Exercises: {exercises}.": "Ukończone serie: {sets}. Ćwiczenia: {exercises}.",
  "Working sets: {count}": "Serie robocze: {count}",
  "Exercises: {exercises} · Sets: {sets}": "Ćwiczenia: {exercises} · Serie: {sets}",
  "Last: {when}": "Ostatnio: {when}",
  "Not done yet": "Jeszcze niewykonane",
  "Training streak (weeks): {count}": "Seria treningów (tygodnie): {count}",
  "Reps: {count}": "Powtórzenia: {count}",
  "Last 12 weeks": "Ostatnie 12 tygodni",
  "previous {range}": "poprzedni okres: {range}",
  "Per {bucket} · {range}": "Na {bucket} · {range}",
  "week": "tydzień",
  "month": "miesiąc",
  "workouts": "treningi",
  "last week": "w zeszłym tygodniu",
  "prior 4 weeks": "w poprzednich 4 tygodniach",
  "{name} {phase} position": "{name} - pozycja {phase}",
  "start": "początkowa",
  "finish": "końcowa",
  "{name} exercise demo": "Pokaz ćwiczenia: {name}",
  "Muscle illustration: {muscle}{secondary}": "Ilustracja mięśni: {muscle}{secondary}",
  "{muscle} bodypart illustration{secondary}": "Ilustracja mięśni: {muscle}{secondary}",
  "; secondary: {muscles}": "; dodatkowe: {muscles}",
  "Muscle map: {view}": "Mapa mięśni: {view}",
  "front": "przód",
  "back": "tył",
  "primary": "główny",
  "secondary": "dodatkowy",
  "inactive": "nieaktywny",
  "Edit {name}": "Edytuj {name}",
  "Remove {name}": "Usuń {name}",
  "Remove set {count}": "Usuń serię {count}",
  "{name} options": "Opcje ćwiczenia {name}",
  "Rest remaining: {time}": "Pozostały czas przerwy: {time}",
  "Set {label} options": "Opcje serii {label}",
  "Use previous: {value}": "Użyj poprzedniej wartości: {value}",
  "Weight ({unit})": "Ciężar ({unit})",
  "Distance ({unit})": "Dystans ({unit})",
  "Title is required": "Tytuł jest wymagany",
  "Title must be at most 120 characters long": "Tytuł może mieć najwyżej 120 znaków",
  "Start time is required": "Godzina rozpoczęcia jest wymagana",
  "Heart rate must be between 30 and 250": "Tętno musi wynosić od 30 do 250",
  "Duration must be longer than zero": "Czas trwania musi być dłuższy niż zero",
  "Enter a valid date and time": "Wprowadź prawidłową datę i godzinę",
  "Name is required": "Nazwa jest wymagana",
  "Name must be at most 80 characters long": "Nazwa może mieć najwyżej 80 znaków",
  "Must not be negative": "Wartość nie może być ujemna",
  "Password must be at least 8 characters long": "Hasło musi mieć co najmniej 8 znaków",
  "Password must be at most 128 characters long": "Hasło może mieć najwyżej 128 znaków",
  "Password must contain at least one uppercase letter": "Hasło musi zawierać co najmniej jedną wielką literę",
  "Password must contain at least one special character": "Hasło musi zawierać co najmniej jeden znak specjalny",
  "Enter your username or email": "Wpisz nazwę użytkownika lub e-mail",
  "Enter your password": "Wpisz hasło",
  "Username must be at least 3 characters long": "Nazwa użytkownika musi mieć co najmniej 3 znaki",
  "Username must be at most 32 characters long": "Nazwa użytkownika może mieć najwyżej 32 znaki",
  "Use letters, digits, '.', '_' and '-' only": "Używaj tylko liter, cyfr oraz znaków '.', '_' i '-'",
  "Invalid email address": "Nieprawidłowy adres e-mail",
  "Passwords do not match": "Hasła nie są takie same",
  "Password cannot contain the username": "Hasło nie może zawierać nazwy użytkownika",
  "Display name must be at most 64 characters long": "Nazwa wyświetlana może mieć najwyżej 64 znaki",
  "Enter your current password": "Wpisz obecne hasło",
  "Use the 11 character YouTube video id": "Wpisz 11-znakowy identyfikator filmu YouTube",
  "FitTune is taking too long to respond. Try again later.": "FitTune odpowiada zbyt długo. Spróbuj ponownie później.",
  "Can't reach FitTune right now. Check your connection.": "Nie można teraz połączyć się z FitTune. Sprawdź połączenie.",
  "The server sent an unexpected response.": "Serwer wysłał nieoczekiwaną odpowiedź.",
  "Unexpected error while saving": "Nieoczekiwany błąd podczas zapisywania",
  "Could not save workout": "Nie udało się zapisać treningu",
  "At most {max}": "Maksymalnie {max}",
  "Must be between {min} and {max}": "Wartość musi wynosić od {min} do {max}",
  "(saved setup)": "(zapisany zestaw)",
  "-week": "-tygodniowa",
  "15 seconds less": "15 sekund mniej",
  "15 seconds more": "15 sekund więcej",
  "8+ characters with an uppercase letter and a symbol.": "Co najmniej 8 znaków, w tym wielka litera i symbol.",
  "Active time": "Czas aktywności",
  "Activity": "Aktywność",
  "Activity type": "Rodzaj aktywności",
  "Add Home, Gym, or a custom setup. Each place has its own equipment list.": "Dodaj dom, siłownię lub własne miejsce. Każde miejsce ma osobną listę sprzętu.",
  "Add exercise": "Dodaj ćwiczenie",
  "Add exercises": "Dodaj ćwiczenia",
  "Add note": "Dodaj notatkę",
  "Add place": "Dodaj miejsce",
  "Add set": "Dodaj serię",
  "Add where you train before your first workout. Each place keeps its own equipment, so exercises match what you have.": "Dodaj miejsce treningu przed pierwszym treningiem. Każde miejsce ma własny sprzęt, więc zobaczysz dostępne tam ćwiczenia.",
  "Add your first exercise to start logging sets.": "Dodaj pierwsze ćwiczenie, aby zacząć zapisywać serie.",
  "Add your first place": "Dodaj pierwsze miejsce",
  "All": "Wszystkie",
  "All equipment": "Cały sprzęt",
  "All muscles": "Wszystkie mięśnie",
  "All workouts": "Wszystkie treningi",
  "All workouts, activities, routines and custom exercises are permanently removed. Enter your password to confirm.": "Wszystkie treningi, aktywności, plany i własne ćwiczenia zostaną trwale usunięte. Wpisz hasło, aby potwierdzić.",
  "Already have an account?": "Masz już konto?",
  "Anatomy: BodyParts3D, © DBCLS, CC BY 4.0": "Anatomia: BodyParts3D, © DBCLS, CC BY 4.0",
  "Appearance": "Wygląd",
  "Archive": "Archiwizuj",
  "Archive exercise": "Archiwizuj ćwiczenie",
  "Archive this place? Existing workouts keep their setup.": "Zarchiwizować to miejsce? Istniejące treningi zachowają swój zestaw sprzętu.",
  "Archived": "Zarchiwizowane",
  "Available equipment": "Dostępny sprzęt",
  "Avg heart rate": "Średnie tętno",
  "Back to home": "Wróć na stronę główną",
  "Back to places": "Wróć do miejsc",
  "Best": "Najlepszy wynik",
  "Best est. 1RM": "Najlepsze szac. 1RM",
  "Best session volume": "Największa objętość sesji",
  "Best set per session": "Najlepsza seria w sesji",
  "Birthday": "Data urodzenia",
  "Bodyweight exercises are always available. Leave all equipment unchecked for a bodyweight-only place.": "Ćwiczenia z masą ciała są zawsze dostępne. Nie zaznaczaj sprzętu, jeśli trenujesz tylko z masą ciała.",
  "Cached places are available for workouts. Connect to add, edit, or archive places.": "Zapisane miejsca są dostępne podczas treningu. Połącz się z internetem, aby dodać, edytować lub archiwizować miejsca.",
  "Cancel": "Anuluj",
  "Cardio describes the activity, not a specific muscle group.": "Kardio opisuje aktywność, a nie konkretną grupę mięśni.",
  "Choose a place": "Wybierz miejsce",
  "Close": "Zamknij",
  "Confirm archive": "Potwierdź archiwizację",
  "Confirm password": "Potwierdź hasło",
  "Connect to save changes to places.": "Połącz się z internetem, aby zapisać zmiany miejsc.",
  "Connect to the internet to sync.": "Połącz się z internetem, aby zsynchronizować dane.",
  "Got an invite?": "Masz zaproszenie?",
  "You need an invite code to create an account.": "Aby utworzyć konto, potrzebujesz kodu zaproszenia.",
  "Invite code": "Kod zaproszenia",
  "FitTune is invite only. Ask an admin for a code.": "Do FitTune można dołączyć tylko na zaproszenie. Poproś administratora o kod.",
  "Invites": "Zaproszenia",
  "FitTune is invite only. Create a code for each person you want to let in.": "Do FitTune można dołączyć tylko na zaproszenie. Utwórz kod dla każdej osoby, którą chcesz zaprosić.",
  "Not available offline yet": "Jeszcze niedostępne offline",
  "It downloads to this device the next time FitTune is online.": "Dane zostaną pobrane na to urządzenie, gdy FitTune znów będzie online.",
  "Offline mode": "Tryb offline",
  "Offline mode is on.": "Tryb offline jest włączony.",
  "FitTune won't use the network; workouts you log are saved on this device and sync when you turn it off.": "FitTune nie będzie używać sieci. Zapisane treningi pozostaną na tym urządzeniu i zsynchronizują się po wyłączeniu trybu offline.",
  "Turn it off in Profile": "Wyłącz go w profilu",
  "Turn off offline mode to sync.": "Wyłącz tryb offline, aby zsynchronizować dane.",
  "Use FitTune without the network, for example with a weak signal at the gym. Workouts are saved on this device and sync when you turn it off. It also turns on by itself while FitTune's servers are unavailable.": "Korzystaj z FitTune bez sieci, na przykład przy słabym zasięgu na siłowni. Treningi są zapisywane na tym urządzeniu i synchronizują się po wyłączeniu trybu offline. Tryb włącza się też automatycznie, gdy serwery FitTune są niedostępne.",
  "FitTune keeps your exercises, routines, places and last {count} workouts on this device so they work without a connection. It syncs automatically whenever it is online.": "FitTune przechowuje ćwiczenia, plany, miejsca i ostatnie {count} treningów na tym urządzeniu, aby działały bez połączenia. Dane synchronizują się automatycznie po połączeniu z internetem.",
  "Sync stopped. Try again.": "Synchronizacja została zatrzymana. Spróbuj ponownie.",
  "Who is it for? (optional)": "Dla kogo? (opcjonalnie)",
  "e.g. Ala from the gym": "np. Ala z siłowni",
  "Expires after": "Wygasa po",
  "1 day": "1 dniu",
  "{count} days": "{count} dniach",
  "Can be used": "Liczba użyć",
  "Once": "Raz",
  "{count} times": "{count} razy",
  "Creating…": "Tworzenie…",
  "Create invite": "Utwórz zaproszenie",
  "{what} copied": "Skopiowano: {what}",
  "Couldn't copy. Select the code and copy it manually.": "Nie udało się skopiować. Zaznacz kod i skopiuj go ręcznie.",
  "New invite code": "Nowy kod zaproszenia",
  "Copy it now. For security the code is not stored and won't be shown again.": "Skopiuj go teraz. Ze względów bezpieczeństwa kod nie jest przechowywany i nie będzie ponownie pokazany.",
  "Code": "Kod",
  "Copy code": "Kopiuj kod",
  "Invite link": "Link zaproszenia",
  "Copy invite link": "Kopiuj link zaproszenia",
  "Active": "Aktywne",
  "Used": "Wykorzystane",
  "Expired": "Wygasłe",
  "Revoked": "Unieważnione",
  "Invite revoked": "Zaproszenie unieważnione",
  "Couldn't revoke the invite. Try again.": "Nie udało się unieważnić zaproszenia. Spróbuj ponownie.",
  "No invites yet.": "Nie ma jeszcze zaproszeń.",
  "No note": "Bez notatki",
  "{used}/{total} used": "Wykorzystano: {used}/{total}",
  "expired": "wygasło",
  "expires": "wygasa",
  "by {name}": "utworzył(a): {name}",
  "Revoke? The code stops working; accounts already created stay.": "Unieważnić? Kod przestanie działać, ale utworzone konta pozostaną.",
  "Revoke": "Unieważnij",
  "Continue “": "Kontynuuj „",
  "Create an account": "Utwórz konto",
  "Create routine": "Utwórz plan",
  "Custom": "Własne",
  "Custom exercise": "Własne ćwiczenie",
  "Dark": "Ciemny",
  "Date": "Data",
  "Delete": "Usuń",
  "Delete account": "Usuń konto",
  "Delete activity": "Usuń aktywność",
  "Delete routine": "Usuń plan",
  "Delete set": "Usuń serię",
  "Delete this routine?": "Usunąć ten plan?",
  "Delete this workout?": "Usunąć ten trening?",
  "Delete workout": "Usuń trening",
  "Delete your account?": "Usunąć konto?",
  "Difficulty": "Poziom trudności",
  "Discard": "Odrzuć",
  "Discard this workout?": "Odrzucić ten trening?",
  "Discard workout": "Odrzuć trening",
  "Display name": "Nazwa wyświetlana",
  "Distance": "Dystans",
  "Distance (": "Dystans (",
  "Distance, 4 weeks": "Dystans, 4 tygodnie",
  "Done": "Gotowe",
  "Duration": "Czas trwania",
  "Edit exercise": "Edytuj ćwiczenie",
  "Edit routine": "Edytuj plan",
  "Effort (1–10)": "Wysiłek (1–10)",
  "Elevation gain (m)": "Suma podejść (m)",
  "Email": "E-mail",
  "Equipment": "Sprzęt",
  "Equipment at": "Sprzęt w",
  "Equipment needed": "Wymagany sprzęt",
  "Est. 1RM": "Szac. 1RM",
  "Every rep": "Każde powtórzenie",
  "Every session you've logged": "Wszystkie zapisane treningi",
  "Everything the exercise needs. It shows up at places that have all of it; leave empty for bodyweight.": "Cały sprzęt potrzebny do ćwiczenia. Pojawi się ono w miejscach, które mają cały ten sprzęt. Zostaw puste dla ćwiczeń z masą ciała.",
  "Exercise": "Ćwiczenie",
  "Exercise demo": "Pokaz ćwiczenia",
  "Exercise library": "Biblioteka ćwiczeń",
  "Exercise notes": "Notatki o ćwiczeniu",
  "Exercise photos: Free Exercise DB": "Zdjęcia ćwiczeń: Free Exercise DB",
  "Exercises": "Ćwiczenia",
  "Farthest": "Najdalszy dystans",
  "Filter by muscle": "Filtruj według mięśnia",
  "Filter by type": "Filtruj według rodzaju",
  "Finish": "Zakończ",
  "Finish & save": "Zakończ i zapisz",
  "Finish a workout and your bests show up here.": "Zakończ trening, a pojawią się tu Twoje rekordy.",
  "Finish workout?": "Zakończyć trening?",
  "Finished workouts show up here with their volume and sets.": "Zakończone treningi pojawią się tu z objętością i liczbą serii.",
  "FitTune keeps your exercises, routines, places and last": "FitTune przechowuje ćwiczenia, plany, miejsca i ostatnie",
  "FitTune's servers are unavailable right now.": "Serwery FitTune są teraz niedostępne.",
  "FitTune's servers are unavailable; try again later.": "Serwery FitTune są niedostępne. Spróbuj ponownie później.",
  "Front & back": "Przód i tył",
  "Goal, progression scheme…": "Cel, plan progresji…",
  "Heaviest weight": "Największy ciężar",
  "History": "Historia",
  "How did it feel?": "Jak się czułeś(-aś)?",
  "How it's tracked": "Sposób zapisu",
  "I am a…": "Jestem…",
  "Instructions": "Instrukcje",
  "It will be removed from your history and stats. This can't be undone.": "Zostanie usunięty z historii i statystyk. Tej czynności nie można cofnąć.",
  "Join FitTune": "Dołącz do FitTune",
  "Keep going": "Kontynuuj",
  "Kilograms": "Kilogramy",
  "Kilometres": "Kilometry",
  "Language": "Język",
  "Last done": "Ostatnio",
  "Library & custom movements": "Biblioteka i własne ćwiczenia",
  "Light": "Jasny",
  "Log": "Zapisz",
  "Log a few workouts to see which muscles you train most.": "Zapisz kilka treningów, aby zobaczyć, które mięśnie trenujesz najczęściej.",
  "Log activity": "Zapisz aktywność",
  "Log sets in seconds at the gym, then dig into volume, records and trends when you are home.": "Zapisuj serie na siłowni w kilka sekund, a w domu analizuj objętość, rekordy i trendy.",
  "Longest": "Najdłużej",
  "Manage": "Zarządzaj",
  "Manage places": "Zarządzaj miejscami",
  "Member since": "Użytkownik od",
  "Metric": "Wskaźnik",
  "Miles": "Mile",
  "Most reps": "Najwięcej powtórzeń",
  "Move down": "Przesuń w dół",
  "Move up": "Przesuń w górę",
  "Muscle": "Mięsień",
  "Muscle distribution": "Rozkład mięśni",
  "Muscle focus": "Pracujące mięśnie",
  "Muscle map: front and back": "Mapa mięśni: przód i tył",
  "Muscles worked": "Pracujące mięśnie",
  "Name": "Nazwa",
  "Name (optional)": "Imię (opcjonalnie)",
  "New": "Nowe",
  "New custom exercise": "Nowe własne ćwiczenie",
  "New routine": "Nowy plan",
  "New to FitTune?": "Nie masz konta FitTune?",
  "No activities": "Brak aktywności",
  "No data": "Brak danych",
  "No exercises match. Create a custom one from the Exercises page.": "Nie znaleziono ćwiczeń. Utwórz własne na stronie Ćwiczenia.",
  "No records yet": "Brak rekordów",
  "No routines yet": "Brak planów",
  "No strength training in this period.": "Brak treningów siłowych w tym okresie.",
  "No working sets completed.": "Nie ukończono żadnych serii roboczych.",
  "No workouts yet": "Brak treningów",
  "Notes": "Notatki",
  "Notes: seat height, grip, how it felt…": "Notatki: wysokość siedzenia, chwyt, odczucia…",
  "Nothing logged yet": "Nic jeszcze nie zapisano",
  "Offline data": "Dane offline",
  "Offline data settings": "Ustawienia danych offline",
  "Open on YouTube": "Otwórz na YouTube",
  "Optional demo video (the 11 characters after “v=”).": "Opcjonalny film pokazowy (11 znaków po „v=”).",
  "Password": "Hasło",
  "Personal records": "Rekordy osobiste",
  "Personal records appear after your first workout.": "Rekordy osobiste pojawią się po pierwszym treningu.",
  "Pick exercises and target sets once, then start the session in one tap at the gym.": "Wybierz ćwiczenia i serie docelowe, a potem rozpocznij trening jednym dotknięciem.",
  "Place name": "Nazwa miejsca",
  "Place type": "Rodzaj miejsca",
  "Plan": "Plan",
  "Plan your first routine": "Zaplanuj pierwszy trening",
  "Plan your go-to sessions once, then start them with a tap.": "Zaplanuj swoje stałe treningi i uruchamiaj je jednym dotknięciem.",
  "Plan your training": "Zaplanuj trening",
  "Pounds": "Funty",
  "Prefer not to say": "Wolę nie podawać",
  "Previous": "Poprzednio",
  "Primary": "Główne",
  "Primary muscle": "Główny mięsień",
  "Primary muscles are red. Secondary muscles are green. Other muscles and bones are grey.": "Główne mięśnie są czerwone, dodatkowe zielone, a pozostałe mięśnie i kości szare.",
  "Profile": "Profil",
  "Profile & settings": "Profil i ustawienia",
  "Profile & units": "Profil i jednostki",
  "Progress": "Postępy",
  "Ready when you are": "Gotowy do treningu?",
  "Recent": "Ostatnie",
  "Records": "Rekordy",
  "Remove exercise": "Usuń ćwiczenie",
  "Repeat": "Powtórz",
  "Repeat workout": "Powtórz trening",
  "Repeat “": "Powtórz „",
  "Reps": "Powtórzenia",
  "Rest": "Przerwa",
  "Rest (s)": "Przerwa (s)",
  "Rest timer": "Minutnik przerwy",
  "Retry": "Ponów",
  "Routines": "Plany",
  "Runs, rides & everything cardio": "Bieganie, jazda i inne aktywności kardio",
  "Runs, rides, walks and swims you log appear here.": "Zapisane biegi, przejazdy, spacery i pływanie pojawią się tutaj.",
  "Same as": "Tyle samo co",
  "Save as routine": "Zapisz jako plan",
  "Save the equipment available at each place you train.": "Zapisz sprzęt dostępny w każdym miejscu treningu.",
  "Search exercises": "Szukaj ćwiczeń",
  "Secondary": "Dodatkowe",
  "Secondary muscles": "Dodatkowe mięśnie",
  "Security": "Bezpieczeństwo",
  "Sessions": "Sesje",
  "Set": "Seria",
  "Set type": "Rodzaj serii",
  "Sets": "Serie",
  "Setup and cues": "Ustawienie i wskazówki",
  "Show all exercises, including other equipment": "Pokaż wszystkie ćwiczenia, także wymagające innego sprzętu",
  "Sign in": "Zaloguj się",
  "Sign in to continue your training.": "Zaloguj się, aby kontynuować trening.",
  "Sign out": "Wyloguj się",
  "Sign out anyway": "Wyloguj mimo to",
  "Skip rest": "Pomiń przerwę",
  "Start": "Rozpocznij",
  "Start a workout": "Rozpocznij trening",
  "Start a workout or log a run - it will show up here.": "Rozpocznij trening lub zapisz bieg, a pojawi się tutaj.",
  "Start empty workout": "Rozpocznij pusty trening",
  "Start with a template": "Zacznij od szablonu",
  "Start workout": "Rozpocznij trening",
  "Started": "Rozpoczęto",
  "Stay signed in": "Pozostań zalogowany(-a)",
  "Suggested equipment only. Review the list to match your setup.": "To tylko sugerowany sprzęt. Sprawdź listę i dostosuj ją do swojego miejsca.",
  "System": "Systemowy",
  "Theme": "Motyw",
  "This page skipped leg day and never showed up.": "Ta strona ominęła dzień nóg i się nie pojawiła.",
  "This week": "Ten tydzień",
  "This workout keeps its saved setup. Select another setup to change it.": "Ten trening zachowa zapisany zestaw sprzętu. Wybierz inny, aby go zmienić.",
  "Time": "Czas",
  "Time range": "Zakres czasu",
  "Time, 4 weeks": "Czas, 4 tygodnie",
  "Title": "Tytuł",
  "Totals": "Łącznie",
  "Track workouts, runs and progress in one place.": "Śledź treningi, biegi i postępy w jednym miejscu.",
  "Tracks": "Pomiar",
  "Training time": "Czas treningu",
  "Trends, volume & records": "Trendy, objętość i rekordy",
  "Try again": "Spróbuj ponownie",
  "Type": "Rodzaj",
  "Unsaved workouts on this device": "Niezapisane treningi na tym urządzeniu",
  "Username": "Nazwa użytkownika",
  "Username or email": "Nazwa użytkownika lub e-mail",
  "Volume": "Objętość",
  "Watch demo": "Obejrzyj pokaz",
  "Watch demo on Vimeo": "Obejrzyj pokaz na Vimeo",
  "Weekly distance": "Tygodniowy dystans",
  "Weekly volume": "Tygodniowa objętość",
  "Weight": "Ciężar",
  "Welcome back": "Witaj ponownie",
  "Working sets by primary muscle": "Serie robocze według głównego mięśnia",
  "Working sets, last 4 weeks": "Serie robocze z ostatnich 4 tygodni",
  "Workout": "Trening",
  "Workout actions": "Działania treningu",
  "Workout complete": "Trening ukończony",
  "Workout notes": "Notatki do treningu",
  "Workout options": "Opcje treningu",
  "Workout place": "Miejsce treningu",
  "Workout title": "Nazwa treningu",
  "Workouts": "Treningi",
  "Workouts this week": "Treningi w tym tygodniu",
  "Workouts you already did from it are kept.": "Ukończone treningi z tego planu pozostaną zapisane.",
  "Workouts you log are saved on this device and sync when you're back online.": "Zapisane treningi pozostaną na tym urządzeniu i zsynchronizują się po połączeniu z internetem.",
  "Works offline. Syncs when you are back.": "Działa offline. Synchronizuje po powrocie do sieci.",
  "You can keep up to": "Możesz mieć maksymalnie",
  "You can keep using the app offline; workouts you log are saved on this device and sync once we're back.": "Możesz nadal korzystać z aplikacji offline. Treningi zapiszą się na tym urządzeniu i zsynchronizują po przywróceniu połączenia.",
  "You haven't logged this exercise yet.": "Nie zapisano jeszcze tego ćwiczenia.",
  "You're offline.": "Brak połączenia z internetem.",
  "YouTube video id": "Identyfikator filmu YouTube",
  "across": "w",
  "counts.": "ma znaczenie.",
  "e.g. Home or Downtown gym": "np. Dom lub Siłownia w centrum",
  "e.g. Sled push": "np. Pchanie sań",
  "e.g. Upper body A": "np. Góra ciała A",
  "exercise": "ćwiczenie",
  "exercises and their sets will be deleted. This can't be undone.": "ćwiczenia i ich serie zostaną usunięte. Tej czynności nie można cofnąć.",
  "exercises ·": "ćwiczeń ·",
  "from this device.": "z tego urządzenia.",
  "more": "więcej",
  "not done": "nieukończone",
  "on another device": "na innym urządzeniu",
  "places. Archive one to add another.": "miejsc. Zarchiwizuj jedno, aby dodać kolejne.",
  "reached the server yet. Signing out now deletes": "dotarło jeszcze do serwera. Wylogowanie teraz usunie",
  "reps": "powtórzenia",
  "sets": "serie",
  "sets ·": "serii ·",
  "training streak": "seria treningów",
  "vs": "w porównaniu z",
  "working": "roboczych",
  "workout": "trening",
  "workouts on this device so they work without a connection. It syncs automatically when you open the app online.": "treningi na tym urządzeniu, aby działały bez połączenia. Synchronizacja następuje automatycznie po otwarciu aplikacji online.",
};
