"""Convert the original MIT MuscleMap paths into FitTune's bundled 2D geometry"""

import argparse
import json
import re
import urllib.request
from pathlib import Path

REVISION = "7dc03071e03052e8bd4f6351e9176994cd28aa7d"
SOURCE = f"https://raw.githubusercontent.com/melihcolpan/MuscleMap/{REVISION}"
ROOT = Path(__file__).resolve().parents[2]
GROUPS = {
    "chest": "chest", "abs": "abs", "obliques": "abs", "biceps": "biceps",
    "triceps": "triceps", "deltoids": "shoulders", "quadriceps": "quadriceps",
    "calves": "calves", "trapezius": "traps", "forearm": "forearms",
    "upperBack": "upper_back", "lowerBack": "lower_back", "gluteal": "glutes",
    "hamstring": "hamstrings",
}
NEUTRAL = {"neck", "hands", "knees", "tibialis", "ankles", "feet", "adductors", "serratus", "hipFlexors", "head", "hair"}


def read(name, directory):
    if directory:
        return (directory / name).read_text()
    path = name if name == "LICENSE" else f"Sources/MuscleMap/Data/{name}"
    with urllib.request.urlopen(f"{SOURCE}/{path}", timeout=30) as response:
        return response.read().decode()


def geometry(side, directory):
    source = read(f"Male{side.title()}Paths.swift", directory)
    regions = []
    for match in re.finditer(r"BodyPartPathData\(\s*slug: \.(\w+),(.*?)\n        \)", source, re.S):
        slug, block = match.groups()
        if slug not in GROUPS and slug not in NEUTRAL:
            continue
        paths = re.findall(r'"([^"\n]+)"', block)
        if not paths:
            raise ValueError(f"No geometry for {side}/{slug}")
        if slug == "upperBack":
            if len(paths) != 6:
                raise ValueError("Review the pinned upper-back path mapping")
            # The two large lateral panels are lats, the four scapular panels are upper back
            regions.append({"name": "lats", "muscle": "lats", "paths": [paths[1], paths[5]]})
            paths = [path for index, path in enumerate(paths) if index not in (1, 5)]
        regions.append({"name": slug, "muscle": GROUPS.get(slug), "paths": paths})
    if not regions:
        raise ValueError(f"No regions parsed for {side}")
    return {"x": 0 if side == "front" else 718, "y": 95, "width": 727, "height": 1280, "regions": regions}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, help="Use downloaded originals for offline regeneration")
    args = parser.parse_args()
    views = {side: geometry(side, args.source_dir) for side in ("front", "back")}
    mapped = {region["muscle"] for view in views.values() for region in view["regions"] if region["muscle"]}
    if mapped != set(GROUPS.values()) | {"lats"}:
        raise ValueError("Missing FitTune muscle groups")
    output = ROOT / "src/features/exercises/body-shapes.generated.ts"
    output.write_text(
        "// Generated by scripts/anatomy/build-muscle-map.py, do not edit by hand\n"
        f"// MuscleMap revision {REVISION}, Copyright (c) 2026 Melih Colpan, MIT\n"
        "// Original licence: public/licenses/muscle-map.txt\n\n"
        f"export const bodyViews = {json.dumps(views, indent=2)} as const;\n"
    )
    licence = ROOT / "public/licenses/muscle-map.txt"
    licence.parent.mkdir(parents=True, exist_ok=True)
    licence.write_text(read("LICENSE", args.source_dir))
    print(f"Generated {output.stat().st_size:,} bytes with {len(mapped)} muscle groups")


if __name__ == "__main__":
    main()
