/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppWorkoutRouteImport } from './routes/_app/workout'
import { Route as AppExercisesIndexRouteImport } from './routes/_app/exercises/index'
import { Route as AppExercisesExerciseIdRouteImport } from './routes/_app/exercises/$exerciseId'
import { Route as AppRoutinesIndexRouteImport } from './routes/_app/routines/index'
import { Route as AppRoutinesRoutineIdRouteImport } from './routes/_app/routines/$routineId'
import { Route as AppRoutinesNewRouteImport } from './routes/_app/routines/new'
import { Route as AppWorkoutsIndexRouteImport } from './routes/_app/workouts/index'
import { Route as AppWorkoutsWorkoutIdRouteImport } from './routes/_app/workouts/$workoutId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesIndexRoute = AppExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesExerciseIdRoute = AppExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesIndexRoute = AppRoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoutineIdRoute = AppRoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesNewRoute = AppRoutinesNewRouteImport.update({
  id: '/routines/new',
  path: '/routines/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsWorkoutIdRoute = AppWorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workout': typeof AppWorkoutRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/routines/new': typeof AppRoutinesNewRoute
  '/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/exercises/': typeof AppExercisesIndexRoute
  '/routines/': typeof AppRoutinesIndexRoute
  '/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workout': typeof AppWorkoutRoute
  '/': typeof AppIndexRoute
  '/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/routines/new': typeof AppRoutinesNewRoute
  '/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/exercises': typeof AppExercisesIndexRoute
  '/routines': typeof AppRoutinesIndexRoute
  '/workouts': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/': typeof AppIndexRoute
  '/_app/exercises/$exerciseId': typeof AppExercisesExerciseIdRoute
  '/_app/routines/$routineId': typeof AppRoutinesRoutineIdRoute
  '/_app/routines/new': typeof AppRoutinesNewRoute
  '/_app/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/_app/exercises/': typeof AppExercisesIndexRoute
  '/_app/routines/': typeof AppRoutinesIndexRoute
  '/_app/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/routines/new'
    | '/workouts/$workoutId'
    | '/exercises/'
    | '/routines/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/activity'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/'
    | '/exercises/$exerciseId'
    | '/routines/$routineId'
    | '/routines/new'
    | '/workouts/$workoutId'
    | '/exercises'
    | '/routines'
    | '/workouts'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/activity'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/workout'
    | '/_app/'
    | '/_app/exercises/$exerciseId'
    | '/_app/routines/$routineId'
    | '/_app/routines/new'
    | '/_app/workouts/$workoutId'
    | '/_app/exercises/'
    | '/_app/routines/'
    | '/_app/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/': {
      id: '/_app/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AppExercisesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/$exerciseId': {
      id: '/_app/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AppExercisesExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/': {
      id: '/_app/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof AppRoutinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/$routineId': {
      id: '/_app/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof AppRoutinesRoutineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines/new': {
      id: '/_app/routines/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof AppRoutinesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/': {
      id: '/_app/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/$workoutId': {
      id: '/_app/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof AppWorkoutsWorkoutIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExercisesExerciseIdRoute: typeof AppExercisesExerciseIdRoute
  AppRoutinesRoutineIdRoute: typeof AppRoutinesRoutineIdRoute
  AppRoutinesNewRoute: typeof AppRoutinesNewRoute
  AppWorkoutsWorkoutIdRoute: typeof AppWorkoutsWorkoutIdRoute
  AppExercisesIndexRoute: typeof AppExercisesIndexRoute
  AppRoutinesIndexRoute: typeof AppRoutinesIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppIndexRoute: AppIndexRoute,
  AppExercisesExerciseIdRoute: AppExercisesExerciseIdRoute,
  AppRoutinesRoutineIdRoute: AppRoutinesRoutineIdRoute,
  AppRoutinesNewRoute: AppRoutinesNewRoute,
  AppWorkoutsWorkoutIdRoute: AppWorkoutsWorkoutIdRoute,
  AppExercisesIndexRoute: AppExercisesIndexRoute,
  AppRoutinesIndexRoute: AppRoutinesIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
